# SLF4J Simple Configuration
org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=true
org.slf4j.simpleLogger.showShortLogName=true

# Логирование для наших классов
org.slf4j.simpleLogger.log.org.example.etl.DatabaseImportService=debug
org.slf4j.simpleLogger.log.org.example.repository.impl=warn
org.slf4j.simpleLogger.log.com.zaxxer.hikari=info

# Запись в файл
org.slf4j.simpleLogger.logFile=error_debug.log
org.slf4j.simpleLogger.levelInBrackets=true
